train: /Users/samedi/Documents/Coding/swans/data/train 
val: /Users/samedi/Documents/Coding/swans/data/val  

# number of classes
nc: 1

# class names
names: ['swan']

translate: 0.1 
scale: 0.2
fliplr: 0.5