path_detector_onnx = r'model/bin/best.onnx'
path_initial_train_dataset = r'/Users/samedi/Desktop/Минприроды'
path_train_dataset = r'data/train'
path_val_dataset = r'data/val'
path_test_dataset = r'data/test'
path_submit = r'data/submit'